// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEA7Q6imxFLITriU9py7LXsjlINGI9HUs',
    appId: '1:185192759282:web:5321b1f339a5feb3bbf56b',
    messagingSenderId: '185192759282',
    projectId: 'expense-tracker-app-3fe99',
    authDomain: 'expense-tracker-app-3fe99.firebaseapp.com',
    storageBucket: 'expense-tracker-app-3fe99.firebasestorage.app',
    measurementId: 'G-0P90QS6540',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkvsLUVqpZ_QEPk-tQxeiuS_dRjflVPHw',
    appId: '1:185192759282:android:c65bf6bb9c55f731bbf56b',
    messagingSenderId: '185192759282',
    projectId: 'expense-tracker-app-3fe99',
    storageBucket: 'expense-tracker-app-3fe99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM234BjB2sRteoVNlGb9K7_bRYoVdgm9E',
    appId: '1:185192759282:ios:859084b0777d7f58bbf56b',
    messagingSenderId: '185192759282',
    projectId: 'expense-tracker-app-3fe99',
    storageBucket: 'expense-tracker-app-3fe99.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );
}
